##################################
## NEW CONFIGS STARTS HERE
##################################

name: Test Terraform Plan And Apply
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: us-east-1
      # AWS_DEFAULT_REGION: us-east-1
      AWS_S3_BUCKET: mx-tf-state-bucket-dev
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_DYNAMO_DB_TABLE: mx-tf-state-table
    
    defaults:
      run:
        working-directory: lab-work-2

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Configure AWS Credentials
        # uses: aws-actions/configure-aws-credentials@v2
        uses: ./.github/workflows/main.yml
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            ${{ env.AWS_REGION }}
      
      - name: Setup Terraform Environment
        uses: ./.github/workflows/main.yml
        with:
          aws-region: ${{ env.AWS_REGION }}
          bucket-name: ${{ env.AWS_S3_BUCKET }}
          dynamo-db-table: ${{ env.TF_DYNAMO_DB_TABLE }}
          working-directory: lab-work-2

      - name: Ensure S3 bucket exists
        run: |
          if ! aws s3api head-bucket --bucket "${{ env.AWS_S3_BUCKET }}" 2>/dev/null; then
            echo "Bucket ${{ env.AWS_S3_BUCKET }} not found; creating…"
            aws s3api create-bucket \
              --bucket "${{ env.AWS_S3_BUCKET }}" \
              --region "${{ env.AWS_REGION }}"
            # (Optional) enable versioning so state file history is preserved:
            aws s3api put-bucket-versioning \
              --bucket "${{ env.AWS_S3_BUCKET }}" \
              --versioning-configuration Status=Enabled
          else
            echo "Bucket ${{ env.AWS_S3_BUCKET }} already exists."
          fi

      - name: Ensure DynamoDB table exists
        run: |
          if ! aws dynamodb describe-table --table-name "${{ env.TF_DYNAMO_DB_TABLE }}" 2>/dev/null; then
            echo "Table ${{ env.TF_DYNAMO_DB_TABLE }} not found; creating…"
            aws dynamodb create-table \
              --table-name "${{ env.TF_DYNAMO_DB_TABLE }}" \
              --attribute-definitions AttributeName=LockID,AttributeType=S \
              --key-schema AttributeName=LockID,KeyType=HASH \
              --billing-mode PAY_PER_REQUEST
          else
            echo "Table ${{ env.TF_DYNAMO_DB_TABLE }} already exists."
          fi

      - name: Terraform Init
        run:  terraform init -upgrade 
        # removed the backend config for now to be in main.tf
            # -backend-config="bucket=${{ env.AWS_S3_BUCKET }}" \
            # -backend-config="region=${{ env.AWS_REGION }}" \
            # -backend-config="key=terraform.tfstate"

      - name: Terraform Plan
        id: plan
        run: terraform plan -out=tfplan

      - name: Terraform Validate 
        run: terraform validate

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan

      # - name: Verify AWS identity
      #   run: aws sts get-caller-identity
