name: Terraform Planner 

on: 
    push: 
        branches:
            - main
    # pull_request:
    #     branches:
    #         - main
    workflow_dispatch:

jobs:
    terraform-planner: 
        name: Terraform Plan
        runs-on: ubuntu-latest
        env: 
            AWS_REGION: ${{ secrets.AWS_REGION }}
            AWS_S3_BUCKET: ${{ secrets.TF_S3_BUCKET }}
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            TF_DYNAMO_DB_TABLE: ${{ secrets.TF_DYNAMO_DB_TABLE }}
            TF_BUCKET_NAME: ${{ secrets.TF_BUCKET_NAME }}

        defaults:
            run:
                working-directory: ./lab-work-2 

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Configure Terraform Environment
              uses: ./.github/actions/configure-tf
              with: 
                aws-region: ${{ env.AWS_REGION }}
                aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
                s3-bucket-name: ${{ env.TF_BUCKET_NAME }}
                dynamo-db-table-name: ${{ env.TF_DYNAMO_DB_TABLE }}
                working-directory: ./lab-work-2

            - name: Terraform Plan
              run: |
                echo "📋 Running Terraform Plan..."
                set +e # Don't exit on error right away
                terraform plan -detailed-exitcode -out=tfplan
                exit_code=$?
                echo "exit_code=$exit_code" >> $GITHUB_OUTPUT
                # terraform plan -out=tfplan
                echo "Terraform Plan completed with exit code $exit_code"

                if [ $exit_code -eq 0 ]; then
                    echo "✅ Terraform Plan succeeded."
                elif [ $exit_code -eq 2 ]; then
                    echo "⚠️ Terraform Plan has changes to apply."
                else
                    echo "❌ Terraform Plan failed with exit code $exit_code."
                    exit $exit_code
                fi
              id: plan
            
            - name: Comment Plan Results
              if: github.event_name == 'push'
              run: |
                echo "📝 Commenting on the pull request with plan results..."
                if [ "${{ steps.plan.outputs.exit_code }}" == 0 ]; then
                    echo "✅ No changes detected in the Terraform plan."
                elif [ "${{ steps.plan.outputs.exit_code }}" == 2 ]; then
                    echo "⚠️ Changes detected in the Terraform plan. Please review."
                else
                    echo "❌ Terraform plan failed. Please check the logs."
                fi

